### ISSUE TITLE
NPE every second after a player sleeps

### ISSUE THREAD

**Issue by ffrejaa** [nkomarn/harbor#12]
I get a NPE in the console every second after a player has slept

I'm on harbor 1.4.4 and Spigot git-Spigot-b0f4c22-2ced023 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

```
[11:37:18] [Server thread/WARN]: java.lang.NullPointerException
[11:37:18] [Server thread/WARN]: 	at techtoolbox.Harbor.ActionBarMessage.run(ActionBarMessage.java:10)
[11:37:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[11:37:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[11:37:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[11:37:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[11:37:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[11:37:18] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[11:37:18] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

This happens on a regular interval of 1 second
Restarting the server fixes this until a player has slept in a bed

Let me know if you need more info

**Comment by monotonehell** [comment]
Can confirm same bug.
