### ISSUE TITLE
Constantly failing

### ISSUE THREAD

**Issue by Dunnoit** [nkomarn/harbor#18]
Using this on a 1.14.2 vanilla world. It works for a little while, then stops working. People go to sleep but even with the % needed, night does not skip.
Only thing that fixes if is a full world restart, which is getting a bit wearisome.

**Comment by ThybeVB** [comment]
Can confirm.

**Comment by compieter-gh** [comment]
has the same issue

[13:13:32] [Server thread/ERROR]: Could not pass event PlayerBedEnterEvent to Harbor v1.5
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[Spigot.jar:git-Spigot-df0eb25-30a6337]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[Spigot.jar:git-Spigot-df0eb25-30a6337]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) ~[Spigot.jar:git-Spigot-df0eb25-30a6337]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) ~[Spigot.jar:git-Spigot-df0eb25-30a6337]
	at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerBedEnterEvent(CraftEventFactory.java:248) ~[Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.EntityHuman.sleep(EntityHuman.java:1247) ~[Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.EntityPlayer.sleep(EntityPlayer.java:921) ~[Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.EntityPlayer.sleep(EntityPlayer.java:915) ~[Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.BlockBed.interact(BlockBed.java:55) ~[Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.IBlockData.interact(SourceFile:282) ~[Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:463) ~[Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1267) ~[Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:13) ~[Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) [Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(SourceFile:135) [Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(SourceFile:114) [Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:895) [Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:888) [Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(SourceFile:99) [Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:871) [Spigot.jar:git-Spigot-df0eb25-30a6337]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:805) [Spigot.jar:git-Spigot-df0eb25-30a6337]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NullPointerException
	at mykyta.Harbor.Util.add(Util.java:77) ~[?:?]
	at mykyta.Harbor.Events.BedEnter.onPlayerBedEnter(BedEnter.java:47) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[Spigot.jar:git-Spigot-df0eb25-30a6337]
	... 24 more

**Comment by nkomarn** [comment]
@Dunnoit @MonstahGames @TheCompieter Give the latest beta a shot! Visit https://harbor.nkomarn.xyz/ to download the beta. Let me know how things go!

**Comment by TheCompieter** [comment]
@nkomarn it improved on stratup but when i sleep in a bed i get this error 
Note: i am using paper 1.14.2 last build as of yesterday atm.

Error on beta build of harbor:

[15:06:14 ERROR]: Could not pass event PlayerBedEnterEvent to Harbor v1.5
java.lang.NullPointerException: null
        at mykyta.Harbor.Util.add(Util.java:75) ~[?:?]
        at mykyta.Harbor.Events.BedEnter.onPlayerBedEnter(BedEnter.java:47) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor102.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.2.jar:git-Paper-94]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.2.jar:git-Paper-94]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.2.jar:git-Paper-94]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:536) ~[patched_1.14.2.jar:git-Paper-94]
        at org.bukkit.craftbukkit.v1_14_R1.event.CraftEventFactory.callPlayerBedEnterEvent(CraftEventFactory.java:250) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.EntityHuman.sleep(EntityHuman.java:1279) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.EntityPlayer.sleep(EntityPlayer.java:1012) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.EntityPlayer.sleep(EntityPlayer.java:1006) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.BlockBed.interact(BlockBed.java:55) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.IBlockData.interact(IBlockData.java:221) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.PlayerInteractManager.a(PlayerInteractManager.java:487) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1393) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:18) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:127) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:105) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aW(MinecraftServer.java:999) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:992) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:91) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:975) ~[patched_1.14.2.jar:git-Paper-94]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.14.2.jar:git-Paper-94]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

**Comment by compieter-gh** [comment]
still an error on latest build as of yesterday of Paper 1.14.2
i am using the last beta of harbor.
Note: when i reload harbor with /harbor reload it works then but thats the only way too get it too work
it wont work when the server just started

[latest.log](https://github.com/nkomarn/Harbor/files/3301612/latest.log)

**Comment by nkomarn** [comment]
Fixed for 1.5.1
