### ISSUE TITLE
Harbor 1.5 - 1.13.2 Backwards Compatibility Not Working Correctly

### ISSUE THREAD

**Issue by SBMous** [nkomarn/harbor#20]
Using the release jar (Distributed through spigotmc.org) of Harbor 1.5 the backwards compatibility doesn't appear to be working as intended. It appears to be attempting to bind to 1.14 and then not correcting to 1.13, might be an issue with it not accounting for paper?

**Server Info**
Running Paper version git-Paper-626 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Java Version '1.8.0_212'

Plugins (27): AnimatedFrames, BuycraftX, CoreProtect, CrazyCrates, CustomCommands, DistributedMobSpawns, Dynmap, Dynmap-WorldGuard, EssentialsX, FishinRoulette, GCore, Harbor, Holographic Displays, LuckPerms, MapManager, NuVotifier, PacketListenerAPI, PlanAnalytics, PlayerHeads, Shopkeepers, SuperbVote, Vault, WorldBorder, WorldEdit, WorldGuard

**Trace**
```
[12:06:23] [Server thread/ERROR]: Could not load 'plugins/Harbor - 1.5.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.14
at org.bukkit.craftbukkit.v1_13_R2.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:226) ~[patched_1.13.2.jar:git-Paper-626]
at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[patched_1.13.2.jar:git-Paper-626]
at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[patched_1.13.2.jar:git-Paper-626]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255) ~[patched_1.13.2.jar:git-Paper-626]
at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:331) ~[patched_1.13.2.jar:git-Paper-626]
at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:235) ~[patched_1.13.2.jar:git-Paper-626]
at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:787) ~[patched_1.13.2.jar:git-Paper-626]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by nkomarn** [comment]
Fixed for the next release (1.5.1).
