### ISSUE TITLE
[Error]Plugin not loading on start

### ISSUE THREAD

**Issue by NoManaSendHelp** [nkomarn/harbor#24]
I get the following error trying to start the server with harbor 1.5.1

Paper 131
MC 1.14.3

```
[02:24:49 ERROR]: Error occurred while enabling Harbor v1.5.1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/apache/commons/io/IOUtils
at mykyta.Harbor.Updater.check(Updater.java:37) ~[?:?]
at mykyta.Harbor.Harbor.onEnable(Harbor.java:52) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.3.jar:git-Paper-131]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.3.jar:git-Paper-131]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.3.jar:git-Paper-131]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.3.jar:git-Paper-131]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.3.jar:git-Paper-131]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.3.jar:git-Paper-131]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:282) ~[patched_1.14.3.jar:git-Paper-131]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:859) ~[patched_1.14.3.jar:git-Paper-131]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.IOUtils
at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_212]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.3.jar:git-Paper-131]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.3.jar:git-Paper-131]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_212]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_212]
... 11 more
[02:24:49 INFO]: [Harbor] Disabling Harbor v1.5.1
```

**Comment by stw222** [comment]
i get the same error on a test server with only harbor 1.5.1b1 essentialsx, vault, and protocol lib on paper 131 1.14.3. harbor 1.5 seemed to work fine though

**Comment by stw222** [comment]
disabling the update check seems to be a temporary fix

**Comment by nkomarn** [comment]
Will be publishing a new version now, let me know if things work on that new version!
