### ISSUE TITLE
Task #102 for Harbor v1.6.1 generated an exception java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: 

### ISSUE THREAD

**Issue by rhystedstone** [nkomarn/harbor#44]
**This gets posted every 2 seconds to console while *Harbor* is enabled**
```[22:43:04] [Server thread/WARN]: [Harbor] Task #102 for Harbor v1.6.1 generated an exception
java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: 
	at xyz.nkomarn.Harbor.task.Checker.getSleeping(Checker.java:64) ~[?:?]
	at xyz.nkomarn.Harbor.task.Checker.checkWorld(Checker.java:31) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_242]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_242]
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175) ~[?:1.8.0_242]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_242]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_242]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_242]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_242]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_242]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_242]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_242]
	at xyz.nkomarn.Harbor.task.Checker.run(Checker.java:27) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[server.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[server.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[server.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[server.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[server.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[server.jar:git-Paper-624]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoSuchMethodError: 
	... 22 more
[22:43:06] [Server thread/WARN]: [Harbor] Task #102 for Harbor v1.6.1 generated an exception
java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: 
	at xyz.nkomarn.Harbor.task.Checker.getSleeping(Checker.java:64) ~[?:?]
	at xyz.nkomarn.Harbor.task.Checker.checkWorld(Checker.java:31) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:1.8.0_242]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) ~[?:1.8.0_242]
	at java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:175) ~[?:1.8.0_242]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_242]
	at java.util.Iterator.forEachRemaining(Iterator.java:116) ~[?:1.8.0_242]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801) ~[?:1.8.0_242]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_242]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_242]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:1.8.0_242]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:1.8.0_242]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_242]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485) ~[?:1.8.0_242]
	at xyz.nkomarn.Harbor.task.Checker.run(Checker.java:27) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[server.jar:git-Paper-624]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[server.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1010) ~[server.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[server.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[server.jar:git-Paper-624]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:837) ~[server.jar:git-Paper-624]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoSuchMethodError: 
	... 22 more``
*As you can see from the log, we are using the latest version (1.6.1) and the essentials soft-dependency is satisfied.*

**Comment by nkomarn** [comment]
Looks like you are using Harbor 1.6.1 on 1.13- Harbor 1.6+ is only compatible with 1.14 and newer because it uses a method that is not available in older versions. If you need support, the oldest version that will be compatible with 1.13 is [Harbor 1.5.3](https://www.spigotmc.org/resources/harbor-a-sleep-enhancement-plugin.60088/download?version=285443).
