### ISSUE TITLE
[1.6.2 Beta 7] NoClassDefFoundError when loading

### ISSUE THREAD

**Issue by LionNatsu** [nkomarn/harbor#66]
```
[20:48:28] [Worker-Main-2/INFO]: Preparing spawn area: 98%
[20:48:28] [Server thread/INFO]: Time elapsed: 2570 ms
[20:48:28] [Server thread/INFO]: [Harbor] Enabling Harbor v1.6.2-SNAPSHOT
[20:48:28] [Server thread/ERROR]: Error occurred while enabling Harbor v1.6.2-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/objects/Object2LongMap
        at xyz.nkomarn.harbor.Harbor.onEnable(Harbor.java:36) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351) ~[spigot-1.16.1.jar:git-Spigot-0287a20-7560f5f]
...
```

**Comment by nkomarn** [comment]
Sorry for the delayed response, but this is an issue that I encountered when initially testing beta 7 on Spigot. I've since made a fix, and released a patched beta 7 with the correct location for the libraries I used in my Discord.

In case you're not in the Discord, here is a direct download link to the JAR: https://cdn.discordapp.com/attachments/671152049185882144/746025401104466001/Harbor-1.6.2-b7-fastutil-SNAPSHOT.jar

Please do let me know if this fixes your issue.

**Comment by LionNatsu** [comment]
Yeah, it fixed the issue! Thank you!
